import {Routes} from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: 'onboarding', pathMatch: 'full' },
  { path: 'onboarding', loadComponent: () => import('./features/onboarding/onboarding.component').then(m => m.OnboardingComponent) },
  { path: 'login', loadComponent: () => import('./features/login/login.component').then(m => m.LoginComponent) },
  { path: 'otp', loadComponent: () => import('./features/otp/otp.component').then(m => m.OtpComponent) },
  { path: 'home', loadComponent: () => import('./features/home/home.component').then(m => m.HomeComponent) },
  { path: 'report/new', loadComponent: () => import('./features/report-new/report-new.component').then(m => m.ReportNewComponent) },
  { path: 'report/success', loadComponent: () => import('./features/report-success/report-success.component').then(m => m.ReportSuccessComponent) },
  { path: 'reports', loadComponent: () => import('./features/report-list/report-list.component').then(m => m.ReportListComponent) },
  { path: 'report/detail/:id', loadComponent: () => import('./features/report-detail/report-detail.component').then(m => m.ReportDetailComponent) },
  { path: 'report/resolved/:id', loadComponent: () => import('./features/report-resolved/report-resolved.component').then(m => m.ReportResolvedComponent) },
  { path: 'notification/:id', loadComponent: () => import('./features/notification/notification.component').then(m => m.NotificationComponent) },
  { path: 'profile', redirectTo: 'home', pathMatch: 'full' },
  { path: 'admin/login', loadComponent: () => import('./features/admin/admin-login/admin-login.component').then(m => m.AdminLoginComponent) },
  { path: 'admin/dashboard', loadComponent: () => import('./features/admin/admin-dashboard/admin-dashboard.component').then(m => m.AdminDashboardComponent) },
  { path: 'admin/reports', loadComponent: () => import('./features/admin/admin-report-list/admin-report-list.component').then(m => m.AdminReportListComponent) },
  { path: 'admin/report/detail/:id', loadComponent: () => import('./features/admin/admin-report-detail/admin-report-detail.component').then(m => m.AdminReportDetailComponent) },
  { path: 'admin/report/ai-process/:id', loadComponent: () => import('./features/admin/admin-report-ai-process/admin-report-ai-process.component').then(m => m.AdminReportAIProcessComponent) },
  { path: 'admin/report/manual-process/:id', loadComponent: () => import('./features/admin/admin-report-manual-process/admin-report-manual-process.component').then(m => m.AdminReportManualProcessComponent) },
  { path: 'admin/report/resolved/:id', loadComponent: () => import('./features/admin/admin-report-resolved/admin-report-resolved.component').then(m => m.AdminReportResolvedComponent) },
  { path: 'admin/notifications', loadComponent: () => import('./features/admin/admin-notification-list/admin-notification-list.component').then(m => m.AdminNotificationListComponent) },
  { path: 'admin/notification/create', loadComponent: () => import('./features/admin/admin-notification-create/admin-notification-create.component').then(m => m.AdminNotificationCreateComponent) },
  { path: 'admin/chats', loadComponent: () => import('./features/admin/admin-chat-list/admin-chat-list.component').then(m => m.AdminChatListComponent) },
  { path: 'admin/chat/:id', loadComponent: () => import('./features/admin/admin-chat-detail/admin-chat-detail.component').then(m => m.AdminChatDetailComponent) },
  { path: 'admin/livestreams', loadComponent: () => import('./features/admin/admin-livestream-list/admin-livestream-list.component').then(m => m.AdminLivestreamListComponent) },
  { path: 'admin/livestream/create', loadComponent: () => import('./features/admin/admin-livestream-create/admin-livestream-create.component').then(m => m.AdminLivestreamCreateComponent) },
  { path: 'admin/statistics', loadComponent: () => import('./features/admin/admin-report-statistics/admin-report-statistics.component').then(m => m.AdminReportStatisticsComponent) },
  { path: 'admin/profile', loadComponent: () => import('./features/admin/admin-profile/admin-profile.component').then(m => m.AdminProfileComponent) },
];
